#!/usr/bin/env python3
"""
Write the committed demo spectra under examples/synthetic/.

The two files are deliberately written in *different* awkward formats -- one
tab-delimited with an instrument preamble, one comma-delimited with descending
wavenumbers and cosmic-ray spikes -- so that the demo exercises the loader's
robustness claims instead of just asserting them in a README.

    python3 make_demo_data.py
"""

from __future__ import annotations

import json
import os

import numpy as np

import synthetic as syn

OUTDIR = os.path.join("examples", "synthetic")

PREAMBLE = """\
# Raman microscope export (synthetic -- generated by make_demo_data.py)
# Laser        : 532 nm
# Grating      : 1800 l/mm
# Exposure     : 10 s x 3 accumulations
# Objective    : 50x
# Columns      : Wavenumber (cm-1)\tIntensity (counts)
"""


def write_tab_with_preamble(path: str, x: np.ndarray, y: np.ndarray) -> None:
    with open(path, "w") as fh:
        fh.write(PREAMBLE)
        for xi, yi in zip(x, y):
            fh.write(f"{xi:.2f}\t{yi:.3f}\n")


def write_csv_descending(path: str, x: np.ndarray, y: np.ndarray) -> None:
    """Comma-delimited, highest wavenumber first -- as some instruments export."""
    with open(path, "w") as fh:
        fh.write("Wavenumber,Intensity\n")
        for xi, yi in zip(x[::-1], y[::-1]):
            fh.write(f"{xi:.2f},{yi:.3f}\n")


def main() -> int:
    os.makedirs(OUTDIR, exist_ok=True)

    # Treated sample: clean-ish, ascending, tab-delimited, instrument preamble.
    xt, yt = syn.make_spectrum(syn.TREATED, seed=1)
    treated_path = os.path.join(OUTDIR, "synthetic_chex.txt")
    write_tab_with_preamble(treated_path, xt, yt)

    # Control sample: descending, comma-delimited, and hit by two cosmic rays.
    # One spike sits at 1100 cm-1, inside the left baseline shoulder, where a
    # mean-based baseline would be dragged by it and a median-based one is not.
    xc, yc = syn.make_spectrum(syn.CONTROL, seed=2, spikes=(1100.0, 2200.0))
    control_path = os.path.join(OUTDIR, "synthetic_control.txt")
    write_csv_descending(control_path, xc, yc)

    truth = {
        "_comment": (
            "Ground truth for the synthetic demo spectra. These are the values "
            "the analysis must recover; tests/ asserts it does."
        ),
        "generator": "make_demo_data.py (seeds 1 and 2)",
        "samples": {},
    }
    for name, path, bands in (
        ("Ch/Ex", treated_path, syn.TREATED),
        ("Control", control_path, syn.CONTROL),
    ):
        truth["samples"][name] = {
            "file": path.replace(os.sep, "/"),
            "bands": {b: {"centre_cm-1": v.centre, "height_counts": v.height,
                          "fwhm_cm-1": v.fwhm} for b, v in bands.items()},
            "ratios": syn.true_ratios(bands),
        }

    truth_path = os.path.join(OUTDIR, "ground_truth.json")
    with open(truth_path, "w") as fh:
        json.dump(truth, fh, indent=2)
        fh.write("\n")

    for p in (treated_path, control_path, truth_path):
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
